### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by bbuckley612** [shanemichaelarcaro/flappy-bird#5]
### Hi there,

Nice program so far! There are just two things that are bugging me...

**To prevent image loading errors when not in root, consider changing the three `image src` attributes in index.html:**

[https://stackoverflow.com/a/27264246](https://stackoverflow.com/a/27264246)

- [ ] `src="/assets/midflap.png"` ↣ `src="assets/midflap.png"` **or** `src="./assets/midflap.png"` 
- [ ] `src="/assets/background.png"` ↣ `src="assets/background.png"` **or** `src="./assets/background.png"`
- [ ] `src="/assets/base.png"` ↣ `src="assets/base.png"` **or** `src="./assets/base.png"`

**Also, to disable scrolling in the browser, add this line to the `html, body` styling in style.css:**

- [ ] `overflow: hidden;`

_Side note: In my opinion, JS is much more useful than Java. I don't know why Mrs. Ricca didn't like JS. Also, are you programming this for class or just for fun? Happy coding!_

**Brian Buckley**
_PV 2020
Purdue 2024_

**Comment by shanemichaelarcaro** [comment]
Hey thanks, I made the changes. I'm programming this for fun since school hasn't started yet and it gives me something to do. I switched to JavaScript because I am currently learning the MERN stack I'm just programming this to try and better myself with the basics.

**Comment by bbuckley612** [comment]
Awesome! I would love to eventually learn more about ME(A/R)N because it's all just JS. Right now, I know a lot more about LAMP and am continuing to learn more all the time. Anyway, I think it's great that you're trying to better your JS skills. JS is the future... at least for the next few years! Good luck!
